[phases.setup]
# Eliminamos nixPkgs para evitar conflictos y usamos solo aptPkgs
# libfreetype6 es el paquete exacto que contiene el archivo .so que falta
 aptPkgs = ["libfreetype6", "fontconfig", "fonts-dejavu", "fontconfig-config"]

[phases.build]
# Forzamos la actualización de la caché de fuentes después de la compilación
cmds = ["./mvnw clean package -DskipTests", "fc-cache -f -v"]
[start]
# Aseguramos el modo headless y que use el JAR generado
cmd = "java $JAVA_OPTS -jar target/*.jar"
